#!/usr/bin/env bash
# ============================================================================
# Bootstrap Script
# ============================================================================
# Reads project.yaml and generates all derived config files:
#   - .env
#   - librechat.yaml
#   - docker-compose.override.yml
#   - Symlinks into librechat/
#
# Usage: ./scripts/bootstrap.sh [--clean]
#   --clean: Remove generated files before regenerating
#
# Dependencies: yq (https://github.com/mikefarah/yq)
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$ROOT_DIR/project.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[bootstrap]${NC} $1"; }
warn() { echo -e "${YELLOW}[bootstrap]${NC} $1"; }
err()  { echo -e "${RED}[bootstrap]${NC} $1" >&2; }
step() { echo -e "${BLUE}[$(( ++STEP_NUM ))/7]${NC} $1"; }

STEP_NUM=0

# --- Preflight ---
if ! command -v yq &>/dev/null; then
    err "yq is required but not installed."
    err "Install: brew install yq (macOS) or snap install yq (Linux)"
    exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
    err "project.yaml not found at $CONFIG"
    exit 1
fi

# --- Clean mode ---
if [[ "${1:-}" == "--clean" ]]; then
    log "Cleaning generated files..."
    rm -f "$ROOT_DIR/.env" \
          "$ROOT_DIR/librechat.yaml" \
          "$ROOT_DIR/docker-compose.override.yml"
    rm -f "$ROOT_DIR/librechat/.env" \
          "$ROOT_DIR/librechat/librechat.yaml" \
          "$ROOT_DIR/librechat/docker-compose.override.yml"
    log "Clean complete."
fi

# --- Helper: read from project.yaml ---
cfg() { yq eval "$1" "$CONFIG"; }

# --- Read config values ---
PROJECT_NAME="$(cfg '.project.name')"
PROJECT_SLUG="$(cfg '.project.slug')"

FEAT_RAG="$(cfg '.features.rag')"
FEAT_SEARCH="$(cfg '.features.search')"
FEAT_VOICE="$(cfg '.features.voice')"
FEAT_CODE="$(cfg '.features.code_interpreter')"
FEAT_WEB_SEARCH="$(cfg '.features.web_search')"
FEAT_MEMORY="$(cfg '.features.memory')"
FEAT_CHAIN="$(cfg '.features.agent_chain')"
FEAT_HANDOFFS="$(cfg '.features.agent_handoffs')"
FEAT_BUILDER="$(cfg '.features.agent_builder')"
FEAT_OCR="$(cfg '.features.ocr')"
FEAT_ARTIFACTS="$(cfg '.features.artifacts')"

DEPLOY_PORT="$(cfg '.deploy.port')"
DEPLOY_DOMAIN="$(cfg '.deploy.domain')"

ARDEN_ENABLED="$(cfg '.arden_fleet.enabled')"

log "Bootstrapping ${PROJECT_NAME} (${PROJECT_SLUG})..."

# ============================================================================
# Step 1: Initialize submodules
# ============================================================================
step "Initializing git submodules..."
if [[ -f "$ROOT_DIR/.gitmodules" ]]; then
    cd "$ROOT_DIR"
    git submodule update --init --recursive 2>/dev/null || warn "Submodule init failed — may need manual setup"
    cd "$ROOT_DIR"
else
    warn "No .gitmodules found — skipping submodule init"
fi

# ============================================================================
# Step 2: Generate .env
# ============================================================================
step "Generating .env..."

cat > "$ROOT_DIR/.env" << ENVEOF
# ==========================================================================
# Generated by bootstrap.sh from project.yaml — do not edit directly
# Re-run: make bootstrap
# ==========================================================================

# --- Server ---
HOST=0.0.0.0
PORT=${DEPLOY_PORT}
APP_TITLE=${PROJECT_NAME}

# --- Database ---
MONGO_URI=mongodb://mongodb:27017/${PROJECT_SLUG}

# --- Search ---
SEARCH=${FEAT_SEARCH}
MEILI_HOST=http://meilisearch:7700
MEILI_MASTER_KEY=CHANGE_ME_meili_master_key

# --- RAG ---
$(if [[ "$FEAT_RAG" == "true" ]]; then
    echo "RAG_API_URL=http://rag_api:8000"
    echo "POSTGRES_DB=${PROJECT_SLUG}_rag"
    echo "POSTGRES_USER=rag"
    echo "POSTGRES_PASSWORD=CHANGE_ME_postgres_password"
    echo "DB_HOST=vectordb"
    echo "DB_PORT=5432"
else
    echo "# RAG disabled — omitting RAG_API_URL"
fi)

# --- LLM Provider ---
# Add your API key(s) here:
$(if [[ "$(cfg '.providers.primary.name')" == "custom" ]]; then
    KEY_ENV="$(cfg '.providers.primary.api_key_env')"
    echo "${KEY_ENV}=CHANGE_ME_your_api_key"
else
    PROVIDER="$(cfg '.providers.primary.name')"
    case "$PROVIDER" in
        anthropic) echo "ANTHROPIC_API_KEY=CHANGE_ME_your_anthropic_key" ;;
        openAI)    echo "OPENAI_API_KEY=CHANGE_ME_your_openai_key" ;;
        google)    echo "GOOGLE_API_KEY=CHANGE_ME_your_google_key" ;;
        *)         echo "# Provider: $PROVIDER — add API key manually" ;;
    esac
fi)

# --- Voice (Pipecat) ---
$(if [[ "$FEAT_VOICE" == "true" ]]; then
    echo "PIPECAT_VOICE_URL=http://pipecat-voice:7860"
    echo "OPENAI_API_KEY=\${OPENAI_API_KEY:-CHANGE_ME_openai_key_for_voice}"
else
    echo "# Voice disabled"
fi)

# --- Code Interpreter ---
$(if [[ "$FEAT_CODE" == "true" ]]; then
    echo "LIBRECHAT_CODE_API_KEY=CHANGE_ME_code_api_key"
else
    echo "# Code interpreter disabled"
fi)

# --- Security (generate unique values for production) ---
CREDS_KEY=CHANGE_ME_32_char_credentials_key
CREDS_IV=CHANGE_ME_16_char_creds_iv
JWT_SECRET=CHANGE_ME_jwt_secret
JWT_REFRESH_SECRET=CHANGE_ME_jwt_refresh_secret

# --- MCP Server Environment ---
$(cfg '.mcp_servers[] | select(.enabled == true) | "# " + .name + "\n" + (.env // {} | to_entries[] | .key + "=" + (.value | tostring))' 2>/dev/null || echo "# No MCP servers enabled")
ENVEOF

log "Generated .env"

# ============================================================================
# Step 3: Generate librechat.yaml
# ============================================================================
step "Generating librechat.yaml..."

# Build capabilities list
CAPS=""
add_cap() { CAPS="${CAPS}    - \"$1\"\n"; }

[[ "$FEAT_CODE" == "true" ]]       && add_cap "execute_code"
add_cap "file_search"
add_cap "actions"
add_cap "tools"
[[ "$FEAT_ARTIFACTS" == "true" ]]  && add_cap "artifacts"
add_cap "context"
[[ "$FEAT_OCR" == "true" ]]        && add_cap "ocr"
[[ "$FEAT_CHAIN" == "true" ]]      && add_cap "chain"
[[ "$FEAT_WEB_SEARCH" == "true" ]] && add_cap "web_search"
add_cap "mcp"

# Build MCP servers block
MCP_BLOCK=""
ENABLED_SERVERS=$(cfg '.mcp_servers[] | select(.enabled == true) | .name' 2>/dev/null || true)
if [[ -n "$ENABLED_SERVERS" ]]; then
    while IFS= read -r server_name; do
        port=$(cfg ".mcp_servers[] | select(.name == \"$server_name\") | .port")
        MCP_BLOCK="${MCP_BLOCK}      ${server_name}:
        type: streamable-http
        url: \"http://${server_name}:${port}/mcp\"
        timeout: 30000
        initTimeout: 10000
"
    done <<< "$ENABLED_SERVERS"
fi

# Build memory block
MEMORY_BLOCK=""
if [[ "$FEAT_MEMORY" == "true" ]]; then
    MEMORY_BLOCK="memory:
  tokenLimit: $(cfg '.memory.token_limit')
  charLimit: $(cfg '.memory.char_limit')
  messageWindowSize: $(cfg '.memory.message_window_size')
  validKeys:
$(cfg '.memory.valid_keys[]' | while read -r key; do echo "    - $key"; done)
  agent:
    provider: $(cfg '.memory.agent.provider')
    model: $(cfg '.memory.agent.model')
"
fi

cat > "$ROOT_DIR/librechat.yaml" << YAMLEOF
# ==========================================================================
# Generated by bootstrap.sh from project.yaml — do not edit directly
# Re-run: make bootstrap
# ==========================================================================
version: 1.2.3

interface:
  endpointsMenu: true
  modelSelect: true
  parameters: true
  sidePanel: true
  presets: false
  webSearch: ${FEAT_WEB_SEARCH}
  fileSearch: ${FEAT_RAG}
  agents:
    use: true
    create: ${FEAT_BUILDER}
    share: ${FEAT_BUILDER}

agents:
  disableBuilder: $(if [[ "$FEAT_BUILDER" == "true" ]]; then echo "false"; else echo "true"; fi)
  recursionLimit: 25
  maxRecursionLimit: 50
  capabilities:
$(echo -e "$CAPS")
$(if [[ -n "$MCP_BLOCK" ]]; then
cat << MCPEOF
  mcpServers:
    allowedDomains:
$(echo "$ENABLED_SERVERS" | while IFS= read -r s; do echo "      - $s"; done)
    servers:
${MCP_BLOCK}
MCPEOF
fi)

${MEMORY_BLOCK}
YAMLEOF

log "Generated librechat.yaml"

# ============================================================================
# Step 4: Generate docker-compose.override.yml
# ============================================================================
step "Generating docker-compose.override.yml..."

# Build MCP service blocks
MCP_SERVICES=""
if [[ -n "$ENABLED_SERVERS" ]]; then
    while IFS= read -r server_name; do
        path=$(cfg ".mcp_servers[] | select(.name == \"$server_name\") | .path")
        port=$(cfg ".mcp_servers[] | select(.name == \"$server_name\") | .port")
        MCP_SERVICES="${MCP_SERVICES}
  ${server_name}:
    build:
      context: ../${path}
      dockerfile: Dockerfile
    container_name: ${server_name}
    ports:
      - \"${port}:${port}\"
    env_file:
      - ../.env
    healthcheck:
      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:${port}/health\"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
"
    done <<< "$ENABLED_SERVERS"
fi

# Pipecat service block
VOICE_SERVICE=""
if [[ "$FEAT_VOICE" == "true" ]]; then
    VOICE_SERVICE="
  pipecat-voice:
    build:
      context: ../pipecat-server
      dockerfile: Dockerfile
    container_name: pipecat-voice
    ports:
      - \"7860:7860\"
    env_file:
      - ../.env
    volumes:
      - type: bind
        source: ../app/prompts
        target: /app/prompts
        read_only: true
    depends_on:
$(echo "$ENABLED_SERVERS" | head -1 | while IFS= read -r s; do
    if [[ -n "$s" ]]; then
        echo "      ${s}:"
        echo "        condition: service_healthy"
    fi
done)
    restart: unless-stopped
"
fi

# API depends_on — only include services that exist
API_DEPENDS=""
if [[ "$FEAT_RAG" == "true" ]]; then
    API_DEPENDS="${API_DEPENDS}
      rag_api:
        condition: service_started"
fi

cat > "$ROOT_DIR/docker-compose.override.yml" << COMPOSEEOF
# ==========================================================================
# Generated by bootstrap.sh from project.yaml — do not edit directly
# Re-run: make bootstrap
# ==========================================================================

services:
  api:
    build:
      context: ..
      dockerfile: app/Dockerfile
    image: ${PROJECT_SLUG}:local
    container_name: ${PROJECT_SLUG}
    environment:
      - CONFIG_PATH=/app/librechat.yaml
      - APP_TITLE=${PROJECT_NAME}
    volumes:
      - type: bind
        source: ../librechat.yaml
        target: /app/librechat.yaml
        read_only: true
$(if [[ -n "$API_DEPENDS" ]]; then
    echo "    depends_on:${API_DEPENDS}"
fi)
${MCP_SERVICES}${VOICE_SERVICE}
COMPOSEEOF

# Remove RAG services from base compose if RAG disabled
if [[ "$FEAT_RAG" != "true" ]]; then
    log "RAG disabled — rag_api and vectordb will not be started"
fi

log "Generated docker-compose.override.yml"

# ============================================================================
# Step 5: Create symlinks
# ============================================================================
step "Creating symlinks..."

LIBRECHAT_DIR="$ROOT_DIR/librechat"
if [[ -d "$LIBRECHAT_DIR" ]]; then
    ln -sf "$ROOT_DIR/.env" "$LIBRECHAT_DIR/.env"
    ln -sf "$ROOT_DIR/librechat.yaml" "$LIBRECHAT_DIR/librechat.yaml"
    ln -sf "$ROOT_DIR/docker-compose.override.yml" "$LIBRECHAT_DIR/docker-compose.override.yml"
    log "Symlinks created in librechat/"
else
    warn "librechat/ directory not found — skipping symlinks (run git submodule update --init)"
fi

# ============================================================================
# Step 6: Generate theme CSS
# ============================================================================
step "Generating theme CSS..."

cat > "$ROOT_DIR/app/styles/theme.css" << CSSEOF
/* ==========================================================================
 * Generated by bootstrap.sh from project.yaml — do not edit directly
 * Re-run: make bootstrap
 * ========================================================================== */

/* --- Custom Fonts --- */
@import url('https://fonts.googleapis.com/css2?family=$(cfg '.theme.font_heading' | tr ' ' '+'):wght@400;600;700&family=$(cfg '.theme.font_body' | tr ' ' '+'):wght@300;400;500;600&family=$(cfg '.theme.font_mono' | tr ' ' '+')&display=swap');

:root {
  /* Brand Colors (HSL) */
  --brand-primary: $(cfg '.theme.primary');
  --brand-accent: $(cfg '.theme.accent');

  /* Typography */
  --font-heading: '$(cfg '.theme.font_heading')', system-ui, sans-serif;
  --font-body: '$(cfg '.theme.font_body')', system-ui, sans-serif;
  --font-mono: '$(cfg '.theme.font_mono')', ui-monospace, monospace;
}

/* Dark mode */
.dark {
  --main-surface-primary: $(cfg '.theme.background_dark');
}

/* Light mode */
.light {
  --main-surface-primary: $(cfg '.theme.background_light');
}
CSSEOF

log "Generated app/styles/theme.css"

# ============================================================================
# Step 7: ARDEN fleet CI (optional)
# ============================================================================
step "Configuring ARDEN fleet..."

if [[ "$ARDEN_ENABLED" == "true" ]]; then
    mkdir -p "$ROOT_DIR/.github/workflows"
    cat > "$ROOT_DIR/.github/workflows/arden-fleet.yml" << 'ARDENEOF'
# ARDEN Fleet PR Review
# Generated by bootstrap.sh — edit project.yaml to disable
name: ARDEN Fleet Review
on:
  pull_request:
    branches: [main, dev]

jobs:
  warden:
    name: "WARDEN: Security Review"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run WARDEN security scan
        run: echo "TODO: Configure WARDEN GitHub Action"

  harden:
    name: "HARDEN: QA Review"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run HARDEN test quality scan
        run: echo "TODO: Configure HARDEN GitHub Action"

  garden:
    name: "GARDEN: Documentation Review"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run GARDEN doc quality scan
        run: echo "TODO: Configure GARDEN GitHub Action"
ARDENEOF
    log "ARDEN fleet CI workflow generated"
else
    log "ARDEN fleet disabled — skipping CI generation"
    rm -f "$ROOT_DIR/.github/workflows/arden-fleet.yml"
fi

# ============================================================================
# Done
# ============================================================================
echo ""
log "Bootstrap complete!"
echo ""
echo "  Next steps:"
echo "  1. Edit .env and replace all CHANGE_ME values with real secrets"
echo "  2. Run 'make up' to build and start all services"
echo "  3. Open http://localhost:${DEPLOY_PORT}"
echo ""
if [[ "$FEAT_VOICE" == "true" ]]; then
    echo "  Voice enabled — Pipecat will be available on port 7860"
fi
if [[ "$FEAT_RAG" == "true" ]]; then
    echo "  RAG enabled — upload files to index them for retrieval"
fi
echo ""
